### ISSUE TITLE
bs4 notfound

### ISSUE THREAD

**Issue by vlain1337** [DarioH0/html-obfuscator#1]
![Screenshot (758)](https://github.com/DarioH0/html-obfuscator/assets/40787695/4423e8a0-1a15-4688-a067-5e29d9db2a67)
im using Arch Linux WSL 2

any solutions?

**Comment by DarioH0** [comment]
you need to download all modules from the python files first.

Get yourself a python package manager like pip (comes by default on arch) and type the following command on your terminal:

`pip install beautifulsoup4`

then, run the `main.py` again with the given instructions and you should have an obfuscated HTML file. (in reality it's javascript but yee)
